# Installs node and then pulls in the dependencies

name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Create assets dir
      run: mkdir assets
    - name: Create assets/css dir
      run: mkdir assets/css/
    - name: Install dependencies
      run: npm ci
    - name: Copy min.css to release dir
      run: cp node_modules/\@exampledev/new.css/new.css assets/css/
    - name: Create dist dir
      run: mkdir newcss
    - name: Move .php release artifacts to dist
      run: mv *.php newcss/
    - name: Move .css release artifacts to dist
      run: mv *.css newcss/
    - name: Move screenshot to dist
      run: mv screenshot.png newcss/
    - name: Move readme to dist
      run: mv readme.txt newcss/
    - name: Archive release artifacts
      uses: actions/upload-artifact@v1
      with:
        name: newcss
        path: newcss/
